#!/usr/bin/env bash

function runSetup() {
    # Ask for the administrator password upfront
    sudo -v

    # Keep-alive: update existing `sudo` time stamp until the script has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

    
    if [ ! -f "./dots.sh" ]; then
        announce "Fetching other files"
        curl -#L https://github.com/mikpir/mac/tarball/main | tar -xzv --strip-components 1
    fi

    # Run sections based on command line arguments
    for ARG in "$@"
    do
        if [ $ARG == "apps" ] || [ $ARG == "all" ]; then
            announce "Installing apps."
            ./apps.sh
        fi
        if [ $ARG == "sway" ] || [ $ARG == "all" ]; then
            announce "Installing sway"
            ./sway.sh
        fi
        if [ $ARG == "docker" ] || [ $ARG == "all" ]; then
            announce "Installing docker"
            ./docker.sh
        fi
        if [ $ARG == "dots" ] || [ $ARG == "all" ]; then
            announce "Copying config files"
            ./dots.sh
        fi
        if [ $ARG == "fonts" ] || [ $ARG == "all" ]; then
            announce "Installing fonts"
            ./fonts.sh
        fi
    done
}

function announce() {
    echo ""
    echo "------------------------------"
    echo $1
    echo "------------------------------"
    echo ""
} 

runSetup $@

announce "Completed running setup, restart your computer to ensure all updates take effect"